import boxes
import os
ofile = open("generatorList.py", "w")
ofile.write("#Generated by generateimports.py, do not edit\n")

for file in os.listdir("../boxes/generators/"):
    if file.endswith(".py") and not file[0] == '_':
        print(file[:-3])
        ofile.write("import  boxes.generators." + file[:-3])
        ofile.write("\n")
ofile.write("import boxes.generators")
ofile.write("\n")
ofile.write("list = [")
for file in os.listdir("../boxes/generators/"):
    if file.endswith(".py") and not file[0] == '_':
        print(file[:-3])
        ofile.write("('', 'boxes.generators." + file[:-3] + "', ''),")
        ofile.write("\n")
ofile.write("('', 'boxes.generators.closedbox', '')]");
ofile.close()
       
    
