#generated by generateimports.py, do not edit
import  boxes.generators.alledges
import  boxes.generators.angledbox
import  boxes.generators.angledcutjig
import  boxes.generators.arcade
import  boxes.generators.bayonetbox
import  boxes.generators.bintray
import  boxes.generators.burntest
import  boxes.generators.cardbox
import  boxes.generators.castle
import  boxes.generators.closedbox
import  boxes.generators.concaveknob
import  boxes.generators.discrack
import  boxes.generators.display
import  boxes.generators.displaycase
import  boxes.generators.displayshelf
import  boxes.generators.dividertray
import  boxes.generators.drillbox
import  boxes.generators.edges
import  boxes.generators.electronicsbox
import  boxes.generators.flexbox
import  boxes.generators.flexbox2
import  boxes.generators.flexbox3
import  boxes.generators.flexbox4
import  boxes.generators.flexbox5
import  boxes.generators.flextest
import  boxes.generators.flextest2
import  boxes.generators.folder
import  boxes.generators.gear
import  boxes.generators.gearbox
import  boxes.generators.heart
import  boxes.generators.hingebox
import  boxes.generators.hooks
import  boxes.generators.integratedhingebox
import  boxes.generators.jigsaw
import  boxes.generators.lamp
import  boxes.generators.laserclamp
import  boxes.generators.laserholdfast
import  boxes.generators.lbeam
import  boxes.generators.magazinefile
import  boxes.generators.makitapowersupply
import  boxes.generators.microrack
import  boxes.generators.nemamount
import  boxes.generators.notesholder
import  boxes.generators.openbox
import  boxes.generators.organpipe
import  boxes.generators.ottobody
import  boxes.generators.ottolegs
import  boxes.generators.ottosoles
import  boxes.generators.paintbox
import  boxes.generators.planetary
import  boxes.generators.planetary2
import  boxes.generators.polehook
import  boxes.generators.pulley
import  boxes.generators.rack10box
import  boxes.generators.rack19box
import  boxes.generators.rack19halfwidth
import  boxes.generators.rackbox
import  boxes.generators.rectangularWall
import  boxes.generators.regularbox
import  boxes.generators.robotarm
import  boxes.generators.rotary
import  boxes.generators.roundedbox
import  boxes.generators.royalgame
import  boxes.generators.shutterbox
import  boxes.generators.silverwarebox
import  boxes.generators.slatwall
import  boxes.generators.slatwallcaliperholder
import  boxes.generators.slatwallconsole
import  boxes.generators.slatwalldrillbox
import  boxes.generators.slatwallplaneholder
import  boxes.generators.slatwallpliersholder
import  boxes.generators.slatwallslottedholder
import  boxes.generators.slatwalltypetray
import  boxes.generators.slatwallwrenchholder
import  boxes.generators.slotwallchiselholder
import  boxes.generators.stachel
import  boxes.generators.storagerack
import  boxes.generators.storageshelf
import  boxes.generators.trafficlight
import  boxes.generators.trayinsert
import  boxes.generators.traylayout
import  boxes.generators.two_piece
import  boxes.generators.typetray
import  boxes.generators.ubox
import  boxes.generators.unevenheightbox
import  boxes.generators.universalbox
import  boxes.generators.waivyknob
import  boxes.generators.winerack
import boxes.generators
list = [('', 'boxes.generators.alledges', ''),
('', 'boxes.generators.angledbox', ''),
('', 'boxes.generators.angledcutjig', ''),
('', 'boxes.generators.arcade', ''),
('', 'boxes.generators.bayonetbox', ''),
('', 'boxes.generators.bintray', ''),
('', 'boxes.generators.burntest', ''),
('', 'boxes.generators.cardbox', ''),
('', 'boxes.generators.castle', ''),
('', 'boxes.generators.closedbox', ''),
('', 'boxes.generators.concaveknob', ''),
('', 'boxes.generators.discrack', ''),
('', 'boxes.generators.display', ''),
('', 'boxes.generators.displaycase', ''),
('', 'boxes.generators.displayshelf', ''),
('', 'boxes.generators.dividertray', ''),
('', 'boxes.generators.drillbox', ''),
('', 'boxes.generators.edges', ''),
('', 'boxes.generators.electronicsbox', ''),
('', 'boxes.generators.flexbox', ''),
('', 'boxes.generators.flexbox2', ''),
('', 'boxes.generators.flexbox3', ''),
('', 'boxes.generators.flexbox4', ''),
('', 'boxes.generators.flexbox5', ''),
('', 'boxes.generators.flextest', ''),
('', 'boxes.generators.flextest2', ''),
('', 'boxes.generators.folder', ''),
('', 'boxes.generators.gear', ''),
('', 'boxes.generators.gearbox', ''),
('', 'boxes.generators.heart', ''),
('', 'boxes.generators.hingebox', ''),
('', 'boxes.generators.hooks', ''),
('', 'boxes.generators.integratedhingebox', ''),
('', 'boxes.generators.jigsaw', ''),
('', 'boxes.generators.lamp', ''),
('', 'boxes.generators.laserclamp', ''),
('', 'boxes.generators.laserholdfast', ''),
('', 'boxes.generators.lbeam', ''),
('', 'boxes.generators.magazinefile', ''),
('', 'boxes.generators.makitapowersupply', ''),
('', 'boxes.generators.microrack', ''),
('', 'boxes.generators.nemamount', ''),
('', 'boxes.generators.notesholder', ''),
('', 'boxes.generators.openbox', ''),
('', 'boxes.generators.organpipe', ''),
('', 'boxes.generators.ottobody', ''),
('', 'boxes.generators.ottolegs', ''),
('', 'boxes.generators.ottosoles', ''),
('', 'boxes.generators.paintbox', ''),
('', 'boxes.generators.planetary', ''),
('', 'boxes.generators.planetary2', ''),
('', 'boxes.generators.polehook', ''),
('', 'boxes.generators.pulley', ''),
('', 'boxes.generators.rack10box', ''),
('', 'boxes.generators.rack19box', ''),
('', 'boxes.generators.rack19halfwidth', ''),
('', 'boxes.generators.rackbox', ''),
('', 'boxes.generators.rectangularWall', ''),
('', 'boxes.generators.regularbox', ''),
('', 'boxes.generators.robotarm', ''),
('', 'boxes.generators.rotary', ''),
('', 'boxes.generators.roundedbox', ''),
('', 'boxes.generators.royalgame', ''),
('', 'boxes.generators.shutterbox', ''),
('', 'boxes.generators.silverwarebox', ''),
('', 'boxes.generators.slatwall', ''),
('', 'boxes.generators.slatwallcaliperholder', ''),
('', 'boxes.generators.slatwallconsole', ''),
('', 'boxes.generators.slatwalldrillbox', ''),
('', 'boxes.generators.slatwallplaneholder', ''),
('', 'boxes.generators.slatwallpliersholder', ''),
('', 'boxes.generators.slatwallslottedholder', ''),
('', 'boxes.generators.slatwalltypetray', ''),
('', 'boxes.generators.slatwallwrenchholder', ''),
('', 'boxes.generators.slotwallchiselholder', ''),
('', 'boxes.generators.stachel', ''),
('', 'boxes.generators.storagerack', ''),
('', 'boxes.generators.storageshelf', ''),
('', 'boxes.generators.trafficlight', ''),
('', 'boxes.generators.trayinsert', ''),
('', 'boxes.generators.traylayout', ''),
('', 'boxes.generators.two_piece', ''),
('', 'boxes.generators.typetray', ''),
('', 'boxes.generators.ubox', ''),
('', 'boxes.generators.unevenheightbox', ''),
('', 'boxes.generators.universalbox', ''),
('', 'boxes.generators.waivyknob', ''),
('', 'boxes.generators.winerack', ''),
('', 'boxes.generators.closedbox', '')]